#!/bin/sh

DATE_SOLID=`date "+%Y%m%d_%H.%M.%S"`
DB_USER=nilmbugsrw

echo ""
echo "You are being prompted ${DB_USER}'s MySQL password below:"
echo ""

mysqldump -u ${DB_USER} -p --default-character-set=utf8 nilmbugs \
   > nilmbugs-dump-${DATE_SOLID}.sql
