#!/bin/sh

MEDIABUGS_RO=http
MEDIABUGS_RW=https
MEDIABUGS_SVN=mediabugs-open.googlecode.com/svn/trunk/

# Check out the mediabugs-open core code into 'nilmbugs', unless
# already present.  Note we could unconditionally check it out -- if
# it were already here, it would just get updated.  But that's not a
# very predictable behavior; better to let updates be manual.
if [ ! -d nilmbugs ]; then
  if svn checkout ${MEDIABUGS_RW}://${MEDIABUGS_SVN} nilmbugs; then
    echo "Checked out read/write copy of mediabugs-open."
  else
    echo "Doing a read-only checkout of mediabugs-open:"
    svn checkout ${MEDIABUGS_RO}://${MEDIABUGS_SVN} nilmbugs
    echo "Checked out read-only copy of mediabugs-open."
  fi
else
    echo "'nilmbugs' directory already present"
fi

# Run the build recipe for MediaBugs.
(cd nilmbugs; make deploy)

# Symlink in the stuff nilmbugs needs that's not already in MediaBugs.
ln -s "../../../pods/lgviolation" nilmbugs/peoplepods/pods/lgviolation
ln -s "../../../themes/nilmbugs" nilmbugs/peoplepods/themes/nilmbugs

# Oh yay, another symlink kluge to match the one in MediaBugs.
ln -s "nilmbugs/peoplepods/PeoplePods.php" PeoplePods.php
ln -s "nilmbugs/peoplepods/lib" lib
